import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Observable;
import java.util.Observer;

/**
 * This GUI class acts as the graphical representation of the chess game. It consists of a Window at the center of the
 * screen. The window itself contains two major areas: a chess board ({@link Board}) and a side panel with additional
 * information and a reset button. The {@link Tile}s of the Board serve as the input sources of the chess match. The
 * events generated by clicking on them is forwarded to a {@link Game} object, which transforms it into moves for the
 * {@link ChessPiece}s located on the {@link Board}.
 */
public class Gui implements Observer {

    private final JTextArea gameLog;
    private final JLabel activeColorLabel;
    private final ImageIcon whiteIcon;
    private final ImageIcon blackIcon;
    private Game game;
    private Board board;
    private final JPanel contentContainer;

    public static void main(String[] args) {
        Gui gui = new Gui();
    }

    /**
     * Creates a new chess Gui. It consists of a Window at the center of the screen. The window itself contains two
     * major areas: a chess board ({@link Board}) and a side panel with additional information and a reset button.
     * The {@link Tile}s of the Board serve as the input sources of the chess match. The events generated by clicking on
     * them is forwarded to a {@link Game} object, which transforms it into moves for the {@link ChessPiece}s located on
     * the {@link Board}.
     */
    public Gui() {
        // Setting up the window
        JFrame window = new JFrame("Chess");

        // Container for both the chess board and the side panel
        contentContainer = new JPanel();
        contentContainer.setLayout(new BoxLayout(contentContainer, BoxLayout.X_AXIS));
        contentContainer.setBorder(new EmptyBorder(5, 5, 5, 5));

        // Container for side elements
        JPanel sidePanel = new JPanel();
        sidePanel.setLayout(new BoxLayout(sidePanel, BoxLayout.Y_AXIS));
        sidePanel.setBorder(new EmptyBorder(0, 5, 0, 0));

        // Label with Icon and text for the currently active color
        whiteIcon = new ImageIcon("resources/KingW.png");
        blackIcon = new ImageIcon("resources/KingB.png");
        activeColorLabel = new JLabel("White's Turn ", whiteIcon, JLabel.CENTER);
        activeColorLabel.setVerticalTextPosition(JLabel.CENTER);
        activeColorLabel.setHorizontalTextPosition(JLabel.RIGHT);
        activeColorLabel.setPreferredSize(new Dimension(150, 50));

        // Game Log
        gameLog = new JTextArea(10, 8);
        gameLog.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(gameLog);

        // Button to reset the board, game and gui
        JButton restartBtn = new JButton("Restart");
        restartBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                restartGame();
            }
        });

        sidePanel.add(activeColorLabel);
        sidePanel.add(scrollPane, BorderLayout.CENTER);
        sidePanel.add(restartBtn);

        // Initialize the board and game
        board = new Board(45);
        game = new Game(board);
        game.addObserver(this);
        contentContainer.add(board);
        contentContainer.add(sidePanel);
        window.add(contentContainer);

        window.pack();
        window.setLocationRelativeTo(null);
        window.setResizable(false);
        window.setVisible(true);

    }

    /**
     * Resets the {@link Game}, {@link Board} and log data to their initial state.
     */
    private void restartGame() {
        contentContainer.remove(board);
        board = new Board(45);
        game = new Game(board);
        game.addObserver(this);
        gameLog.setText("");
        setActiveColor(ChessColor.WHITE);
        contentContainer.add(board, 0);
        contentContainer.revalidate();
    }

    /**
     * Sets the color of the player who is currently playing to the provided {@link ChessColor}. This updates the Label
     * in the top right corner of the window, by showing an icon of the according color.
     *
     * @param color the color of the now active player
     */
    private void setActiveColor(ChessColor color) {
        if (color == ChessColor.WHITE) {
            activeColorLabel.setIcon(whiteIcon);
            activeColorLabel.setText("White's Turn");
        } else {
            activeColorLabel.setIcon(blackIcon);
            activeColorLabel.setText("Black's Turn");
        }
    }

    /**
     * Updates the gui with new information from the corresponding {@link Game}. The Game notifies observing gui's every
     * time a move has ended. The included data is either a String with move information (e.g. "WHITE is checkmate") or
     * the {@link ChessColor} of the now active {@link Player}. This information is used to update the game log or the
     * panel that displays the active Color.
     *
     * @param o the observed Game
     * @param arg either a log entry (String) or the color of an active player (ChessColor)
     */
    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof String) {
            gameLog.append(arg + "\n");
        } else if (arg instanceof ChessColor){
            setActiveColor((ChessColor) arg);
        }
    }
}
